export const AIRPORTS: Record<string, { name: string; city: string; state: string }> = {
  ATL: { name: "Hartsfield-Jackson Atlanta", city: "Atlanta", state: "GA" },
  LAX: { name: "Los Angeles International", city: "Los Angeles", state: "CA" },
  ORD: { name: "O'Hare International", city: "Chicago", state: "IL" },
  DFW: { name: "Dallas/Fort Worth International", city: "Dallas", state: "TX" },
  DEN: { name: "Denver International", city: "Denver", state: "CO" },
  JFK: { name: "John F. Kennedy International", city: "New York", state: "NY" },
  SFO: { name: "San Francisco International", city: "San Francisco", state: "CA" },
  SEA: { name: "Seattle-Tacoma International", city: "Seattle", state: "WA" },
  LAS: { name: "Harry Reid International", city: "Las Vegas", state: "NV" },
  MCO: { name: "Orlando International", city: "Orlando", state: "FL" },
  MIA: { name: "Miami International", city: "Miami", state: "FL" },
  CLT: { name: "Charlotte Douglas International", city: "Charlotte", state: "NC" },
  EWR: { name: "Newark Liberty International", city: "Newark", state: "NJ" },
  PHX: { name: "Phoenix Sky Harbor International", city: "Phoenix", state: "AZ" },
  IAH: { name: "George Bush Intercontinental", city: "Houston", state: "TX" },
  BOS: { name: "Logan International", city: "Boston", state: "MA" },
  MSP: { name: "Minneapolis-Saint Paul International", city: "Minneapolis", state: "MN" },
  DTW: { name: "Detroit Metropolitan Wayne County", city: "Detroit", state: "MI" },
  FLL: { name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", state: "FL" },
  LGA: { name: "LaGuardia Airport", city: "New York", state: "NY" },
  BWI: { name: "Baltimore/Washington International", city: "Baltimore", state: "MD" },
  SLC: { name: "Salt Lake City International", city: "Salt Lake City", state: "UT" },
  PHL: { name: "Philadelphia International", city: "Philadelphia", state: "PA" },
  DCA: { name: "Ronald Reagan Washington National", city: "Washington", state: "DC" },
  IAD: { name: "Washington Dulles International", city: "Dulles", state: "VA" },
  HNL: { name: "Daniel K. Inouye International", city: "Honolulu", state: "HI" },
  MDW: { name: "Chicago Midway International", city: "Chicago", state: "IL" },
  SAN: { name: "San Diego International", city: "San Diego", state: "CA" },
  TPA: { name: "Tampa International", city: "Tampa", state: "FL" },
  PDX: { name: "Portland International", city: "Portland", state: "OR" },
  EZE: { name: "Ministro Pistarini International", city: "Buenos Aires", state: "AR" },
  GCM: { name: "Owen Roberts International", city: "Grand Cayman", state: "KY" },
};

export const DEFAULT_AIRPORTS = ["MIA", "JFK", "EWR", "EZE"];
